apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-app
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/equalamount/gitops.git
    targetRevision: HEAD
    path: dummy-app
    # plugin:
    #   name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
