apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-app
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/equalamount/gitops.git
    targetRevision: HEAD
    path: dummy-app
    # plugin:
    #   name: argocd-vault-plugin-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  data:
    configManagementPlugins: |
      - name: argocd-vault-plugin-kustomize
        generate:
          command: ["sh", "-c"]
          args: ["kustomize build . > all.yaml && argocd-vault-plugin generate all.yaml"]
