apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    namespace: vault
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://helm.releases.hashicorp.com"
    targetRevision: 0.14.0
    chart: vault
    helm:
      parameters:
        - name: injector.externalVaultAddr
          value: "https://vault.csi.local:8200"
  project: "test"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
