apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-adds
  namespace: argocd
spec:
  project: test
  source:
    repoURL: https://github.com/equalamount/gitops.git
    targetRevision: HEAD
    path: hashicorp-vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
