apiVersion: v1
stringData:
  VAULT_ADDR: http://vault-agent
  AVP_AUTH_TYPE: github
  AVP_GITHUB_TOKEN: Github Token
  AVP_TYPE: vault
kind: Secret
metadata:
  name: vault-credentials
  namespace: argocd
type: Opaque
# Don't forget to add this to argocd-repo-server like this:
# envFrom:
# - secretRef:
#     name: vault-configuration
