apiVersion: v1
kind: Service
metadata:
  name: argo-server
spec:
  type: NodePort
  selector:
    app: argo-server
  ports:
    - name: web
      port: 2746
      targetPort: 2746
      nodePort: 30002
